---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-nginx-ingress-controller-tox-py39
        - k8sapp-nginx-ingress-controller-tox-flake8
        - k8sapp-nginx-ingress-controller-tox-pylint
        - k8sapp-nginx-ingress-controller-tox-metadata
        - k8sapp-nginx-ingress-controller-tox-bandit
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-nginx-ingress-controller-tox-py39
        - k8sapp-nginx-ingress-controller-tox-flake8
        - k8sapp-nginx-ingress-controller-tox-pylint
        - k8sapp-nginx-ingress-controller-tox-metadata
        - k8sapp-nginx-ingress-controller-tox-bandit
    post:
      jobs:
        - stx-nginx-ingress-controller-armada-app-upload-git-mirror

- job:
    name: k8sapp-nginx-ingress-controller-tox-py39
    parent: openstack-tox-py39
    description: |
      Run py39 test for k8sapp-nginx-ingress-controller
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-nginx-ingress-controller/*
    vars:
      tox_extra_args: -c python3-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-nginx-ingress-controller-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp-nginx-ingress-controller
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-nginx-ingress-controller/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-nginx-ingress-controller-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp-nginx-ingress-controller
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-nginx-ingress-controller-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp-nginx-ingress-controller
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-nginx-ingress-controller/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-nginx-ingress-controller-tox-bandit
    parent: tox
    description: |
      Run bandit test for k8sapp-nginx-ingress-controller
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-nginx-ingress-controller/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c python3-k8sapp-nginx-ingress-controller/k8sapp_nginx_ingress_controller/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-nginx-ingress-controller-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/nginx-ingress-controller-armada-app to
      github.com/starlingx/nginx-ingress-controller-armada-app
    vars:
      git_mirror_repository: starlingx/nginx-ingress-controller-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-nginx-ingress-controller-armada-app-github-secret3
        pass-to-parent: true

- secret:
    name: stx-nginx-ingress-controller-armada-app-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - gPPTZDmxC1t+MjPLFBe2T+fKHwVHUQjBH0NzFPehaB/YPUeFl05TW8zROWYCNLMzHpLYR
          BNSz419dJgkgtdC+KQ+U3rnBNwN0RXhETrnoKYXSe3tnWP106Q4VJdXo2takVOhebvxbD
          WBGHIuuwt3amO74D/ixfFioLX8ywu22SOoYrxt1A+VobVGkn1srwmL9VjdkU09XSP9Thp
          JEXZtSrnn3m0swf0w6XsPe/Ea5FyE3vNuWbyR/N0VzEbfeRlzbx9eYpTk/XNUr04bEzYr
          E6E7S/TMeDd5u/sSWbyrGnjhJs4Mb6U+XjUR9Bz7D+AvuRziVFnNWMP1dRXFTZTu314xs
          zKxromLaM2ItUlUJsHeuvgp9xn0i7NqvtfcZrIi9Izdzn29/C9l3JEk7z3mVGwLgqhVGf
          v+mQsc3BIUnPHtK6s3lGSqn254ccpA8n76ZwWpPB1MVipbap0DehdLcIGSuPNpx/OuoQW
          5eh5FKc9lfUAtZ+YegHBj/H/XxBkx30xNGQynUCPBYbSlCOGKFzagUYVciloQvrD1qPQU
          O5YA1eKjzogIGjqTz4TOgZJMYV0L2BemF3XNvX+ym9ubymxPrt7+ik5grPhMPli5J2bws
          1hjuTE5W8S8cqq6FzXQhSZw/cKjLiikylrV4buh6Gc/Vvvun1X8C6b5u3lLy2k=
        - Ay3Lwbx5IYB8FPglAWxV6RLmji774dEq9NpBPqOJR6j2Rk6HsklSURAbjytWkiYLeVs+H
          0Es7rXldtS3ocqHnfsdPj1kPkIlzdrGhcloeC7VGD3/o0g83h66kawmVYLxh4HSpAOGPs
          GwWAtu3rQmGiGs8eqteFamvYFc3GW93YfKDKzmjCfHEkgWd5VIGEKVjJ5G0QsFYSWLAHU
          ifQxNsa1W5d9YGcy9DV46Z58PKFpQ5F3iJGPfDnxHmS00TAac0nqw2re2iM0Lu7/Rwfmi
          6URqIgjYIMceNLyctYDKAtJfgj0FKpRoB0PfydwsYtQSEDL7qq608ALP8kokbBumdG/3a
          fFNEMhD4VyBL/3++i9j4hleBKB2h3bx/Gok1CZ2hbtfx3Wf2MKirSO+Jzqj+gseSiEacT
          AubTxvh0eQb5WAm3rwGkTwY2Hs4K41AwZ1274qHWfmd/Btbr+sfoKL/kdnUkFHuLy5vK+
          KtRZowy77yJ8hGn91kYfdSRUtVk2YpFsUwMH/9VFGbyHsRAfBoOY/QmoGvUSr9ESHMTP7
          Zw1lL0nJfrxMvEr3d1iliNiEJAVZfRk3RCYEASJw5fmyoPoM1yMBXIgfX+xOrE6nrszRw
          yY5Jxig90Wu4kLsKmRnTr2kY0KmhONvDJU+hUOA4+fyWQgEWYhvxO+hm7BZVA4=
        - Ww/sFvPV/j/Zlj/bnAZuqbX3Ir123lm6hsSxX0DFcjkHBHOcmIMGy0GOzybSr031G0lXs
          Xp0wz7xKYh4+09lZF68oLDP1KkTKPoxolY1tUI3hTl6IdZG1LUKmUDPJKN0U+moIdNsKs
          Zs9EuhkfVO3m5fmAVNq7zitM3zqKPaOJi9PSjHa6EChR1m4eUcurs9/nGk6AlKl2l0v2S
          expAPGLkN8XshO2uOSe819CBQ/uxFKJYlx64ByC2TsRU9WwO3oa5IP85ZHeB0ltyH8RIg
          yvQ/mQs23L0/f2b+QGDtVgRaGVRRDRTVhFjGQl9X/O8C/FhZ4SlDDEMHSQhl+Id8V+Vr3
          P8EsB2IEBH0gYd4D9UpkwfAZslWIY/g1/dnuRHu+kxqI18Z7pDXrPK0DLQ8BzCeml2C7Q
          rmckh+yLznmMVFtFtjB2skJS/xQqFYWfZbGbAEu5rEIPQ69XITMP9TCZcng/bmxa05NsK
          DDEP7nTgz2HXd0wBC70DGr+OK9sfs5oJeQHiXRys7yvpdp9m763usA3Aj2jY5Z8UXb+97
          a0Siml479ghVRG0uLEM7q3XWBZIaLax5gVbbc6wOAX48/t7bFtf2gr6gWaFRfXA3NnOyu
          UVTDFl0G4HiraFVVnXW0ajfKbgq4qUZM/S4imPagmzj6W8vzTY6OMkPJWwW7II=
        - hce6ZE0ieyaW1Y0UCoocGnVPazox7HsDGagvXvrYFJtNb8F7BTVg+4KqDUyJ6F6VN+/MP
          4XhiOyx/2wzul6qBGOe2LIZ3BUBh8L/pZitJZA6ib6pAt5ccM2K9Um3gexXXIGIHU10dq
          if1x/s0rKCyWs27IKWSPVHV1lRqlejPVm+nbEDSDJn7g282DSiVP9R3dVZb85ZkRAO/VK
          2/86kzt3nDqWyg3NCDyoeE88IA5OKpDYK2EWu7ms+10uI/PijBGu6W75v7ta5Iuvp+wrW
          pGAtov7AHkc06XL9GXA+6ql+tmWJaBcRLem71pnhg0ybW5trjVjAOdPGAHosAy2TjH/kP
          6+WP5l5e7WRZJ2fGcAfUoWoF0gVMAtLuEn9Mbf5be0VfB4Yim1BZW7+scqPaLLDD+KCjS
          Yw2t4SD+yNFkcTv2F7CdvSgwqjczFebxvL4LLgSfFMV8V5WmvgNTH08DsTm71ngE+AB/K
          BIUTUVFHV8x8yslotB2Bd/xEGKNT0/VGd88BKkzs1FiIuMcVXnY4m/8vEvWzJEyg8jfVT
          RSWAO16IHtKPhkyr84X+rSi781SzyyCGvBBECGXtGfJjIX1NFi8NJN+cb92tsbc7J/1Ng
          8vBjr3jSR0K70O8qalyY4UbuJ6Kl0UGIBvRUXImlBBkqzm4cvSlrM/0xuLTDwA=
        - cUdmBae0BCfhFmU4OivE4SNpA2sdJAN2sxzMGkiKlZ9cYKk4seJxaQxInkAlroH3RI32u
          FuNJJqbC9qbfCT6CRuwgj/cdzAXA/vdmaDOoz9cdoyicKQicdxpjnCLslNFNeB85sc4US
          oSL+2EDcoqfx2ZtwugQobNKToqzF//8pcA9RN48jrnvhN9mbauoQPxg4aPxn6yKXbZG4L
          idyfNqu8PTNepeafZFjn8efroZjqUaOigKjVQpDC/4yJyIcLp+J3aQd4jMOArj5FdiSBH
          3nnWYieNBOIBB0xMyccn/N9uX2Gai3w0yPbC3i9htx9nGkCLMQWBk0xM+uIHD6frNnyns
          LYIzg5mdv2JRNWk1E7CARbB/p7Sag3xBow61dk2r3KkCKge3uuWTS0tE1ji5GpIwoDyVj
          R0F6gpo1sF/rwuFEpKFjjSaw755LBh93yZRTwBSJbFeXC/m/S6qWbNat/8D4XBG/8+Jq3
          UVFoxszIFUZXlwErAzZeTcFdhgr5MQmrIheVIzUWJunLYSkzbuh4qpjcB+q1PkJhW+P5S
          g1Q7cYQ7IxJB7JzMqLlyEEN7N/C+o5ynvq2qUnwjp7ttrnLogrmI12Xkg8toXLBdYgN3J
          YmVJH5p4JleXdNhELhY44ImA9hiS3blyZOksEa68cEEnTLaYCFDjM35ZdJCM80=
        - NS0AD54l/62iaHOeNu05b/4CNee2eVYabpSoBfuEYeUiCFULpelR/WLxJVS2rcva1zVcV
          i2FG/557BO7sH40d7967boezI9Zx5oOqJ/Bg2g2WHWW1NlFX89FfbhsFFaifrWVdh8eUO
          BVRoQU+iqPHdjqBSiTPUFj3l5ZG3r7Px4FVfrNa+4g0/MFY4C5gF9qZfsFR+WLSF3VgwY
          x10hp2QbjRwcGUaXFlh0nZVVxuRGnpZ3R6wRRLyiXIL0+fUhh194Z8kmaC6L3URmrdb0f
          SggfRAQgZi7uaOg2xOcBoPxs8lpM5pAe/lGwE5gBp0dMMIxOal9lhmyvFXHPYHB6IKEOZ
          74k8fwNKqJZE5Jq6DeRWmNOnpdsWCI0Zq0HM7pNWYztnqGo4VtskoyZ+vQXWcjNeSGBms
          1cVN0wl+S5LtSeMNuOxn1rkY+B0eIL4f6oH60QFcnMEICMkYBlG/4WxhirAR3wcraRQTo
          BYnVDtyHvaszhB4newOnFse9fAPvDUyz6Q2Q8rIf7ljLQm73TgLqrCO6Xzn6lPCr+kZar
          /xScGe5num5QEfRWsgFnY5v1GwBiXZdpmF4YGjOISXUjXKUws1nDNFatGXKJRjclrx3l9
          yqb/CDQIKKRqcEf1n1uP5nbnf8OsBAH9/JwUQHJ4rH2IJfXB+riwwHiD06NtRw=
        - R/qI+OQmYqp6bOREWVnJp/wxKaRLdTm+hWHkUuM7zBzKziSt2MB48MiBvlHeuhD4xj1Fi
          Q/6i+lXZ+L16781QmlB/FKsGVIzNkKdUMXrjKvFouKoq1GXCozJdyE1o4cCftkI9PBK2g
          v0wph2FSikwwh+92MGO5Ux6HEBcaDCc7pH6tBr8OEQDzyZfwldBHFN//0gP1wEZ3F6lRG
          +AezykLo3N/uy0jJwisfSIzzKoqNADsLjaRETRVq5/Oxrrk0PxJgPeqLKHt2GAkdEhZfj
          mySdDTt34PB3o6fyyAw7B6/adlLe6Fv9N/gI2TKCKNbKg60zpmAgfGWvEvqBqfW3WuHMi
          5viEtMpcV2NSswHXv89+t5DkhQlxXTPXAVWbZraSDz0JsWFJrlUuD/uhvYWXgFxtyoLLR
          mqnZOjL0nrTphsBxs9DjE/0Aj+FUucC8Egu1yo9oyR1KORxhK3u+Yfef0vybQTlaj38YK
          z5pcJNthntFIRx1QQxsdxu8OR6lCPLMHW8KsknFinuDnyHgR2n6sYgvoRwP/zTX+2QHjf
          QkRyHf8tLiHgjVaSrfxTcwaUJKAhews3KpC5u1XdvEDQTrG0CsTYh7ZXOSZ2RcMd0403p
          ohowuIdBlUsbUmr2Qs1Ebb08VCThOjjaStNfRTpTWZiXEEpnAPfR6OF2zgZTco=
