#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: ks-ingress-nginx
  labels:
    chart_group: ingress-nginx
spec:
  releaseName: ic-nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: ingress-nginx-static-overrides
      valuesKey: ingress-nginx-static-overrides.yaml
    - kind: Secret
      name: ingress-nginx-system-overrides
      valuesKey: ingress-nginx-system-overrides.yaml
